version: '2'
services:
    demo3withws-app:
        image: demo3withws
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://demo3withws-postgresql:5432/demo3withws
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demo3withws-postgresql:
        extends:
            file: postgresql.yml
            service: demo3withws-postgresql
