version: '2'
services:
    demo3withws-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/demo3withws/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=demo3withws
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
